### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by tobiashm**
This fixes an issue with some tests exiting early because of an explicit `return` statement in a `Proc`.
At the same time, some require statements were added to test files, to make it possible to run them individually.

### CODE REVIEW

**Comment by tobiashm** [comment]
Notice: This also includes the commit from #85 
That wasn't my intent, but it should be no problem if #85 is also merged (before this PR)

**Comment by tobiashm** [comment]
Given that this, #85 & #84 is merged, it will be possible to add MRI 2.1, 2.2 and jruby-head to the Travis CI build env list, with all passing.

**Comment by jesperronn** [comment]
@dennisreimann I would appreciate if you can look at these pull requests and merge them, given that the tests passes and this is a roadblock for upgrading ruby-openid to Ruby 2.2

@tobiashm could you perhaps provide a new pull-request with all PR changes from #84, #85 and #86

**Comment by jesperronn** [comment]
@dennisreimann thanks! Are you also releasing a new version?

**Comment by dennisreimann** [comment]
Yes, I'll also add the travis builds for the recent ruby versions and will release a new version as soon as possible.

**Comment by jesperronn** [comment]
:+1:

On Thu, Mar 5, 2015 at 1:35 PM, Dennis Reimann <notifications@github.com>
wrote:

> Yes, I'll also add the travis builds for the recent ruby versions and will
> release a new version as soon as possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openid/ruby-openid/pull/86#issuecomment-77356507>.
>



-- 

Jesper Rønn-Jensen
NineConsult
Mobile: +45 2989 1822

Blog http://justaddwater.dk/
jesperrr@gmail.com (Private e-mail and Google Talk IM)

**Comment by dennisreimann** [comment]
Since everything is passing with the most recent ruby versions too, I just pushed out v2.7.0 - enjoy!
Thanks @tobiashm and @jesperronn for the participation :) :cake:

**Comment by jesperronn** [comment]
My pleasure :) thanks for your time and effort maintaining :)

On Thu, Mar 5, 2015 at 1:52 PM, Dennis Reimann <notifications@github.com>
wrote:

> Since everything is passing with the most recent ruby versions too, I just
> pushed out v2.7.0 - enjoy!
> Thanks @tobiashm <https://github.com/tobiashm> and @jesperronn
> <https://github.com/jesperronn> for the participation :) [image: :cake:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openid/ruby-openid/pull/86#issuecomment-77358511>.
>



-- 

Jesper Rønn-Jensen
NineConsult
Mobile: +45 2989 1822

Blog http://justaddwater.dk/
jesperrr@gmail.com (Private e-mail and Google Talk IM)

**Comment by dennisreimann** [comment]
@jesperronn @tobiashm right now I'm not using the gem anymore myself and I'm doing less ruby work in general. That's why this gem lacks attention and to me it seems the other maintainers do not follow what's going on here.

I'd like to pass this on to someone who can maintain the gem better than I'm doing it right now - anyone of you being interested in taking care of it?

**Comment by tobiashm** [comment]
@dennisreimann well, we're depending on the gem for several of our applications, so we have some interest in keeping it maintained. I would be ok with taking care of it.

**Comment by ktdreyer** [comment]
Thanks @tobiashm for these test suite fixups!

**Pull request merged**
